// results
export const FETCH_RESULTS = 'FETCH_RESULTS';

export const TOGGLE_ALIGNMENTS_COLLAPSED = 'TOGGLE_ALIGNMENTS_COLLAPSED';
export const TOGGLE_FACET = 'TOGGLE_FACET';


// submission form
export const SUBMIT_JOB = 'SUBMIT_JOB';
export const TEXTAREA_CHANGE = 'TEXTAREA_CHANGE';
export const TOGGLE_DATABASE_CHECKBOX = 'TOGGLE_DATABASE_CHECKBOX';
export const SELECT_ALL_DATABASES = 'SELECT_ALL_DATABASES';
export const DESELECT_ALL_DATABASES = 'DESELECT_ALL_DATABASES';

export const TOGGLE_DATABASES_COLLAPSED = 'TOGGLE_DATABASES_COLLAPSED';
export const EXAMPLE_SEQUENCE = 'EXAMPLE_SEQUENCE';
export const CLEAR_SEQUENCE = 'CLEAR_SEQUENCE';
export const FILE_UPLOAD = 'FILE_UPLOAD';

export const FETCH_RNACENTRAL_DATABASES = 'FETCH_RNACENTRAL_DATABASES';