export const TOGGLE_ALIGNMENTS_COLLAPSED = 'TOGGLE_ALIGNMENTS_COLLAPSED';
export const RELOAD_RESULTS = 'RELOAD_RESULTS';
export const SCROLL_RESULTS = 'SCROLL_RESULTS';
export const SORT_RESULTS = 'SORT_RESULTS';

export const SUBMIT_JOB = 'SUBMIT_JOB';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const FETCH_RNACENTRAL_DATABASES = 'FETCH_RNACENTRAL_DATABASES';