name: Mirror to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.ebi.ac.uk/RNAcentral/rnacentral-sequence-search-embed.git
          git push gitlab '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
